name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && git pull origin main
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && docker stop groq || true
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && docker rm groq || true
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && docker build -t groq .
            cd ${{ secrets.SERVER_DEPLOY_PATH }} && docker run -d -p 5555:5555 groq
